export default [
  {
    id: 1,
    image: "banana.jpg",
    name: "Wild plant",
    location: "Eldoret, kenya",
  },
  {
    id: 2,
    image: "cocoa.jpg",
    name: "Wild plant",
    location: "Nairobi, kenya",
  },
  {
    id: 3,
    image: "scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
  },
  {
    id: 4,
    image: "banana.jpg",
    name: "Wild plant",
    location: "Mombasa, kenya",
  },
  {
    id: 5,
    image: "cocoa.jpg",
    name: "Wild plant",
    location: "Nakuru, kenya",
  },
  {
    id: 6,
    image: "scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
  },
  {
    id: 7,
    image: "scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
  },
  {
    id: 8,
    image: "banana.jpg",
    name: "Wild plant",
    location: "Mombasa, kenya",
  },
  {
    id: 9,
    image: "cocoa.jpg",
    name: "Wild plant",
    location: "Nakuru, kenya",
  },
  {
    id: 10,
    image: "scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
  },
  {
    id: 11,
    image: "banana.jpg",
    name: "Wild plant",
    location: "Eldoret, kenya",
  },
  {
    id: 12,
    image: "cocoa.jpg",
    name: "Wild plant",
    location: "Nairobi, kenya",
  },
  {
    id: 13,
    image: "scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
  },
  {
    id: 14,
    image: "banana.jpg",
    name: "Wild plant",
    location: "Mombasa, kenya",
  },
  {
    id: 15,
    image: "cocoa.jpg",
    name: "Wild plant",
    location: "Nakuru, kenya",
  },
  {
    id: 16,
    image: "scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
  },
  {
    id: 17,
    image: "scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
  },
  {
    id: 18,
    image: "banana.jpg",
    name: "Wild plant",
    location: "Mombasa, kenya",
  },
  {
    id: 19,
    image: "cocoa.jpg",
    name: "Wild plant",
    location: "Nakuru, kenya",
  },
  {
    id: 20,
    image: "scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
  },
];
