export default [
  {
    id: 1,
    image: "src/images/banana.jpg",
    name: "Banana plant",
    location: "Kisii, kenya",
    openSpots: 0,
    Quantity: 0,
  },
  {
    id: 2,
    image: "src/images/cocoa.jpg",
    name: "Cocoa plant",
    location: "Kiambu, kenya",
    openSpots: 0,
    Quantity: 0,
  },
  {
    id: 3,
    image: "src/images/scaled.jpeg",
    name: "Tea plant",
    location: "Eldoret, kenya",
    openSpots: 3,
    Quantity: 0,
  },
  {
    id: 4,
    image: "src/images/banana.jpg",
    name: "Wild plant",
    location: "Mombasa, kenya",
    openSpots: 4,
  },
  {
    id: 5,
    image: "src/images/cocoa.jpg",
    name: "Wild plant",
    location: "Nakuru, kenya",
    openSpots: 7,
  },
  {
    id: 6,
    image: "src/images/scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
    openSpots: 0,
  },
  {
    id: 7,
    image: "src/images/scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
    openSpots: 1,
  },
  {
    id: 8,
    image: "src/images/banana.jpg",
    name: "Wild plant",
    location: "Mombasa, kenya",
    openSpots: 3,
  },
  {
    id: 9,
    image: "src/images/cocoa.jpg",
    name: "Wild plant",
    location: "Nakuru, kenya",
    openSpots: 2,
  },
  {
    id: 10,
    image: "src/images/scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
    openSpots: 0,
  },
  {
    id: 11,
    image: "src/images/banana.jpg",
    name: "Wild plant",
    location: "Eldoret, kenya",
    openSpots: 1,
  },
  {
    id: 12,
    image: "src/images/cocoa.jpg",
    name: "Wild plant",
    location: "Nairobi, kenya",
    openSpots: 3,
  },
  {
    id: 13,
    image: "src/images/scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
    openSpots: 5,
  },
  {
    id: 14,
    image: "src/images/banana.jpg",
    name: "Wild plant",
    location: "Mombasa, kenya",
    openSpots: 3,
  },
  {
    id: 15,
    image: "src/images/cocoa.jpg",
    name: "Wild plant",
    location: "Nakuru, kenya",
    openSpots: 0,
  },
  {
    id: 16,
    image: "src/images/scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
    openSpots: 9,
  },
  {
    id: 17,
    image: "src/images/scaled.jpeg",
    name: "Wild plant",
    location: "Kitui, kenya",
    openSpots: 1,
  },
  {
    id: 18,
    image: "src/images/banana.jpg",
    name: "Wild plant",
    location: "Mombasa, kenya",
    openSpots: 3,
  },
  {
    id: 19,
    image: "src/images/cocoa.jpg",
    name: "Wild plant",
    location: "Nakuru, kenya",
    openSpots: 0,
  },
  {
    id: 20,
    image: "src/images/scaled.jpeg",
    name: "Tea plant",
    location: "Meru, kenya",
    openSpots: 13,
  },
];
